# Generated by Django 5.1.6 on 2025-02-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_routeschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routeschedule',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Schedule'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
