# Generated by Django 5.1.6 on 2025-02-07 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_routeschedule_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routeschedule',
            options={'ordering': ['start_date']},
        ),
        migrations.RenameField(
            model_name='routeschedule',
            old_name='scheduled_date',
            new_name='start_date',
        ),
        migrations.AlterUniqueTogether(
            name='routeschedule',
            unique_together={('route', 'start_date')},
        ),
        migrations.AlterField(
            model_name='routeschedule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_schedules', to='routes.route'),
        ),
        migrations.RemoveField(
            model_name='routeschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='routeschedule',
            name='start_time',
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('route_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_time', to='routes.routeschedule')),
            ],
            options={
                'unique_together': {('route_schedule', 'day_of_week')},
            },
        ),
    ]
