# Generated by Django 5.1.5 on 2025-01-24 22:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'merchandisers',
            },
        ),
        migrations.CreateModel(
            name='OutletMerchandiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('merchandiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandisers.merchandiser')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.outlet')),
            ],
            options={
                'db_table': 'outlet_merchandisers',
                'unique_together': {('outlet', 'merchandiser')},
            },
        ),
    ]
