# Generated by Django 5.1.5 on 2025-01-16 12:23

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandiser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'merchandisers',
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OutletMerchandiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchandiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandisers.merchandiser')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.outlet')),
            ],
            options={
                'db_table': 'outlet_merchandisers',
                'unique_together': {('outlet', 'merchandiser')},
            },
        ),
        migrations.AddField(
            model_name='merchandiser',
            name='outlets',
            field=models.ManyToManyField(through='merchandisers.OutletMerchandiser', to='outlets.outlet'),
        ),
    ]
