# Generated by Django 5.1.5 on 2025-01-24 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandisers', '0001_initial'),
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandiser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='merchandiser',
            name='email',
            field=models.EmailField(default='[email protected]', max_length=254),
        ),
        migrations.AddField(
            model_name='merchandiser',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='merchandiser',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='merchandiser',
            name='outlets',
            field=models.ManyToManyField(through='merchandisers.OutletMerchandiser', to='outlets.outlet'),
        ),
        migrations.AddField(
            model_name='merchandiser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='merchandiser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
