# Generated by Django 5.1.5 on 2025-01-25 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandisers', '0002_merchandiser_created_merchandiser_email_and_more'),
        ('outlets', '0002_outlet_latitude_outlet_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outletmerchandiser',
            name='channel_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='outlets.channeltype'),
        ),
        migrations.AddField(
            model_name='outletmerchandiser',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='outletmerchandiser',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='merchandiser',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='merchandiser',
            name='first_name',
            field=models.CharField(default='Joe', max_length=50),
        ),
        migrations.AlterField(
            model_name='merchandiser',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
    ]
