# Generated by Django 5.1.5 on 2025-01-16 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('channel_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'channel_types',
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('outlet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('channel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.channeltype')),
            ],
            options={
                'db_table': 'outlets',
            },
        ),
    ]
