# Generated by Django 5.1.5 on 2025-01-30 08:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchandisers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'channel_types',
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.channeltype')),
                ('merchandisers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_outlets', to='merchandisers.merchandiser')),
            ],
            options={
                'db_table': 'outlets',
            },
        ),
    ]
