# Generated by Django 5.1.5 on 2025-01-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0002_outlet_latitude_outlet_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlet',
            old_name='outlet_id',
            new_name='id',
        ),
    ]
