# Generated by Django 5.1.5 on 2025-01-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0002_alter_outlet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlet',
            old_name='merchandisers',
            new_name='merchandiser',
        ),
    ]
